POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxhcyIsImlkIjoiNjQyNThkMTQ3MWEzNmQyY2YzZDE4NDUxIiwiaWF0IjoxNjgwMTgyNTg2fQ.E48D9dzsrw3505CguCg-jkqppKjGKYlvy86H2bzRzgM

{
  "title": "Go To Statement Considered Harmful",
  "author": "Edsger W. Dijkstra",
  "url": "http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html",
  "likes": 5
}