POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxhcyIsImlkIjoiNjQyNjJiMjE5MWQxOGE1NmE3ZTk1YjhhIiwiaWF0IjoxNjgwMjIzNDY3fQ.j4Em3qpjY0n4iQdXwRuEtRl-rtxP7yAnSJx4Q6-t5Ug

{
  "title": "First class tests",
  "author": "Robert C. Martin",
  "url": "http://blog.cleancoder.com/uncle-bob/2017/05/05/TestDefinitions.htmll",
  "likes": 10
}